#Here’s a clean automation setup for your Terraform remote state backend provisioning. You can choose either a Makefile or a shell script depending on your workflow style.

AWS_REGION=ap-south-1
AWS_BUCKET=my-terraform-state-bucket
DDB_TABLE=terraform-locks
GCP_BUCKET=my-terraform-state-bucket
GCP_PROJECT_ID=your-project-id
GCP_REGION=us-central1

aws-backend:
    aws s3api create-bucket \
        --bucket $(AWS_BUCKET) \
        --region $(AWS_REGION) \
        --create-bucket-configuration LocationConstraint=$(AWS_REGION)
    aws s3api put-bucket-versioning \
        --bucket $(AWS_BUCKET) \
        --versioning-configuration Status=Enabled
    aws dynamodb create-table \
        --table-name $(DDB_TABLE) \
        --attribute-definitions AttributeName=LockID,AttributeType=S \
        --key-schema AttributeName=LockID,KeyType=HASH \
        --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 \
        --region $(AWS_REGION)

gcp-backend:
    gsutil mb -p $(GCP_PROJECT_ID) -c standard -l $(GCP_REGION) gs://$(GCP_BUCKET)/
    gsutil versioning set on gs://$(GCP_BUCKET)


#Run:
#make aws-backend
# or
#make gcp-backend

